### ISSUE TITLE
Move action into web page

### ISSUE THREAD

**Issue by BevanR** [Biomatters/biomatters-dev-tools#3]
Inject an HTML element into the page to do the copy action.  E.g.

![screen shot 2016-09-05 at 3 42 11 pm](https://cloud.githubusercontent.com/assets/325176/18236923/725bcea6-737f-11e6-8735-34ef9a370771.png)
### Icon:

![link](https://cloud.githubusercontent.com/assets/325176/18236890/391ab5bc-737f-11e6-9a55-d451ec52a586.png)

Source; 
- http://c.dryicons.com/images/icon_sets/symbolize_icons_set/png/128x128/link.png
- license unknown

**Comment by thomaspaulin** [comment]
Source Site: http://dryicons.com/icon/symbolize-icons-set/link/
Licences linked to on the same page.

Edit: The free one looks like it's too restrictive to use when bundling in a browser extension

**Comment by thomaspaulin** [comment]
Going with https://www.iconfinder.com/icons/62914/chain_link_seo_tags_icon#size=40
